[package]
name = "lab-1-guessing-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.3.14"

[[bin]]
name = "guessing_game"
path = "src/main.rs"